credentials:
  usernames:
    user1:
      email: user1@example.com
      name: User One
      password: $2b$12$QAJ8eU1F4Rs6UGxSTdgiL.uQMDGJYZuP18BSQuLi2FDY8t0i7o0eG
cookie:
  expiry_days: 30
  key: some_signature_key_A1B2C3
  name: finora_auth
preauthorized:  # Wrong key
  emails:
    - user1@example.com
